name: smart_tasbeeh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_animate: ^4.5.2
  fl_chart: ^1.1.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon_v1.png
  adaptive_icon_foreground: assets/icons/app_icon_v1.png
  adaptive_icon_background: "#0E3B2E"

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Variable.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Variable.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Variable.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Variable.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Variable.ttf
          weight: 800
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Variable.ttf
          weight: 400
        - asset: assets/fonts/NotoNaskhArabic-Variable.ttf
          weight: 500
        - asset: assets/fonts/NotoNaskhArabic-Variable.ttf
          weight: 600
        - asset: assets/fonts/NotoNaskhArabic-Variable.ttf
          weight: 700
